package com.simplemobiletools.smsmessenger.language_convertors.lang_maps

object Geo {
    val translitMap = mapOf(
        "a" to "ა",
        "b" to "ბ",
        "g" to "გ",
        "d" to "დ",
        "e" to "ე",
        "v" to "ვ",
        "w" to "ვ",
        "z" to "ზ",
        "t" to "თ",
        "i" to "ი",
        "ქ'" to "კ",
        "l" to "ლ",
        "m" to "მ",
        "n" to "ნ",
        "o" to "ო",
        "ფ'" to "პ",
        "ზჰ" to "ჟ",
        "r" to "რ",
        "s" to "ს",
        "თ'" to "ტ",
        "u" to "უ",
        "p" to "ფ",
        "f" to "ფ",
        "k" to "ქ",
        "გჰ" to "ღ",
        "q" to "ყ",
        "სჰ" to "შ",
        "ცჰ" to "ჩ",
        "თს" to "ც",
        "c" to "ც",
        "დზ" to "ძ",
        "ც'" to "წ",
        "ჩ'" to "ჭ",
        "ქჰ" to "ხ",
        "x" to "ხ",
        "j" to "ჯ",
        "h" to "ჰ",
        "--" to "—"
    )
}

